services:
  - type: web
    name: pdfcowboy-compress
    runtime: python
    rootDir: api
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    nativePackages:
      - ghostscript
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
